# Generated by Django 4.1.4 on 2023-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('employee', 'employee')], default='employee', max_length=20),
        ),
    ]
